---
galaxy_info:
  author: Alfred Meshcheryakov
  description: Prometheus monitoring system configuration and management
  license: MIT
  company: none
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
  - monitoring
  - prometheus
  - metrics
  - alerts
  - alerting

dependencies: []
